# Change these first
owner: EndlessMedia-Cluster # Your GitHub organization or username, where this repository lives
repo: status.endlessmedia.me # The name of this repository
sites:
  - name: Knightcrawler Stremio Addon
    url: https://knightcrawler.endlessmedia.me/stream/movie/tt0023694.json
    __dangerous__body_down_if_text_missing: White Zombie
    assignees:
      - EndlessMedia-Cluster
    expectedStatusCodes:
      - 200
  - name: TorrentIO (not EendlessMedia) Addon
    url: https://torrentio.strem.fun/realdebrid=$RD_KEY/stream/movie/tt0023694.json
    __dangerous__body_down_if_text_missing: White Zombie
    assignees:
      - EndlessMedia-Cluster
    expectedStatusCodes:
      - 200
  - name: Comet Stremio Addon
    url: https://comet.endlessmedia.me
    assignees:
      - EndlessMedia-Cluster
    expectedStatusCodes:
      - 200
  - name: Zilean
    url: https://zilean.endlessmedia.me/healthchecks/ping
    assignees:
      - EndlessMedia-Cluster
    expectedStatusCodes:
      - 200
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  baseUrl: /status.endlessmedia.me
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
